name: schedule_controller
description: Perform several different tasks daily. Very simple and useful timer. It is easy to use.
version: 0.1.0
author: Tenkai Ruri<babichan@outlook.com>
homepage: https://github.com/TenkaiRuri/schedule_controller

environment:
  sdk: '>=1.22.0 <3.0.0'