name: schedule_controller
description: A task scheduler controller Performs several different tasks daily. Straightforward and useful timer.
version: 0.1.3+1
author: Tenkai Ruri<babichan@outlook.com>
homepage: https://github.com/TenkaiRuri/schedule_controller

environment:
  sdk: '>=1.22.0 <3.0.0'